### ISSUE TITLE
getting 'sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.auroradataapi'

### ISSUE THREAD

**Issue by myounus96** [chanzuckerberg/sqlalchemy-aurora-data-api#12]

**Comment by myounus96** [comment]
Jst removed `slim: true` from [serverless framework](https://www.serverless.com/) yml and issue solved.

**Comment by wufire** [comment]
Thank you for following up with this fix! Exact issue I was having
