### ISSUE TITLE
NoRegionError: You must specify a region

### ISSUE THREAD

**Issue by nicpayne713** [chanzuckerberg/sqlalchemy-aurora-data-api#19]
I have an Aurora MySQL instance up and running which I can connect and interact with normally via MySQL Workbench and the database integration tool with PyCharm Pro. When I go to create my sqlalchemy engine and connect as follows:
```
cluster_arn="arn:aws:rds:us-east-1:123456789:cluster:sensitive-name-ue1-dev-cluster"
secret_arn="arn:aws:secretsmanager:us-east-1:123456789:secret:my-special-secret"
conn_uri='mysql+auroradataapi://myuser:specialpassword@sensitive-name.us-east-1.rds.amazonaws.com:3306/mydb'
engine=create_engine(conn_uri, connect_args=dict(aurora_cluster_arn=cluster_arn, secret_arn=secret_arn)
```

I get the following error:

```
botocore.exceptions.NoRegionError: You must specify a region.
```
The region is specified in all the usual places to my knowledge and I don't see a way to explicitly pass.

**Comment by victorlin** [comment]
Are you setting the environment variable `AWS_DEFAULT_REGION`? I ran into the same error when I didn't have it set.

**Comment by nicpayne713** [comment]
I apologize for the late reply here. It is unfortunate but I've moved into a different group and the project I needed this on has been tabled until a replacement is found. I will close for now but if the team has the same issues I'll advise on the environment variable and point them to this bug if it persists.

Thank you

**Comment by tdg5** [comment]
I ran into this also. `AWS_DEFAULT_REGION` is one option that works.

Another is to manually construct the boto3 client with a region and include it in the `connect_args`, something like this:
```
connect_args = dict(
    aurora_cluster_arn=my_config.aurora_cluster_arn,
    rds_data_client=boto3.client(
        aws_access_key_id=my_config.aws_access_key_id,
        aws_secret_access_key=my_config.aws_secret_access_key,
        region_name=my_config.cluster_region,
        service_name="rds-data",
    ),
    secret_arn=my_config.secret_arn,
)
```
